name: Set and Print Environment Variable

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RELEASE_TAG: ${{ github.event.release.tag_name | cut -c 2- }}
    steps:
      - name: Print environment variable
        run: echo "RELEASE_TAG=$RELEASE_TAG"
