name: Image tag

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set hub_frontend_image_version
        id: set_version
        run: echo "::set-output name=version::${{ github.event.release.tag_name | cut -c 2- }}"
