name: Image tag

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set hub_frontend_image_version
        id: set_version
        run: |
          release_tag=${{ github.event.release.tag_name }}
          hub_frontend_image_version=$(echo $release_tag | cut -c 2-)
          echo "::set-output name=version::$hub_frontend_image_version"

      - name: Print hub_frontend_image_version
        run: echo "hub_frontend_image_version: ${{ steps.set_version.outputs.version }}"
