name: Set and Print Environment Variable

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variable
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          RELEASE_TAG=$(echo $TAG_NAME | cut -c 2-)
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Print environment variable
        run: |
          echo "RELEASE_TAG=$RELEASE_TAG"
