name: On Demand Expiry Update
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
      action:
        required: false
        description: "Action"
        type: string
        default: "update"
        
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
      action:
        required: false
        description: "Action for"
        type: string
        options: 
         - delete
         - update
        
      
jobs:
  ondemand-env-expiry:
    name: Update ondemand expiry date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python Script
        env:
          DEPLOY_NAMESPACE: ${{ inputs.environment }}
          EXPIRY_REDIS_PASSWORD: ${{ secrets.EXPIRY_REDIS_PASSWORD}}
          ACTION: ${{ inputs.action }}
        run: |
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
              echo "workflow_dispatch"
          else
              echo "workflow_call"
          fi
          sudo apt-get install -y python3-pip 
          python3 -m pip install --upgrade pip
          pip3 install datetime redis pytz
          python3 updateEnvExpiry.py $ACTION
      - name: Inputs username (workflow call)
        if: ${{ inputs.environment }} != ''
        run: echo ${{ inputs.environment }}

      - name: Inputs username (workflow dispatch)
        if: ${{ github.event.inputs.environment }} != ''
        run: echo ${{ github.event.inputs.environment }}
  successful-job:
    name: Test success
    runs-on: ubuntu-latest
    needs: [ondemand-env-expiry]
    steps:
      - name: script
        run: echo "Hello"
     
