name: On Demand Expiry Update
on:
  workflow_call:
    secrets: 
      EXPIRY_REDIS_PASSWORD:
        required: true
        description: "Expiry redis password"
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
      action:
        required: true
        description: "Action"
        type: string
        
        
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
      action:
        required: true
        description: "Action"
        type: choice
        options:
        - update
          
      
jobs:
  ondemand-env-expiry:
    name: Update ondemand expiry date
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: File
        run: |
          cat <<EOF >> ./ecosystem.config.ts
                    NODE_ENV: $EXPIRY_REDIS_PASSWORD
                    EOF
          cat ./ecosystem.config.ts
        env:
          EXPIRY_REDIS_PASSWORD: ${{ secrets.EXPIRY_REDIS_PASSWORD}}
      - name: Python Script
        env:
          DEPLOY_NAMESPACE: ${{ inputs.environment }}
          EXPIRY_REDIS_PASSWORD: ${{ secrets.EXPIRY_REDIS_PASSWORD}}
          ACTION: ${{ inputs.action }}
        run: |
          sudo apt-get install -y python3-pip 
          python3 -m pip install --upgrade pip
          pip3 install datetime redis pytz
          echo $ACTION
          if [ $ACTION = "update" ]; then
            echo "updatedddddddd"
          fi
          python3 updateEnvExpiry.py $ACTION
      
  successful-job:
    name: Test success
    runs-on: ubuntu-latest
    needs: [ondemand-env-expiry]
    steps:
      - name: script
        run: echo "Hello"
     
