name: Test
on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
  repository_dispatch:
    types: [publish_blog]
jobs:
  test-123:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: |
          echo ${{ inputs.environment}}
  run-script:
    name: Test secret
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Python Script
        with:
          URL: ${{ secrets.URL}}
          CI_TOKEN: ${{ secrets.CI_TOKEN}}
        run: |
          echo $URL
          sudo apt-get install -y \
          python3 \
          python3-pip \
          curl
          python3 -m pip install --upgrade pip
          pip3 install requests
          pip3 install datetime
          pip3 install redis
          python3 test.py
