name: Print
on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Identifier for your environment"
        type: string
  repository_dispatch:
    types: [publish_blog]
jobs:
  validate-namespace:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hi
        run: |
          echo "Hi"
  set-env-expiry:
    uses: joelkbiju12/HeadoutAssignment/.github/workflows/test.yaml@main
    with:
      environment: ${{ inputs.environment}}
      action: "update"
